#!/bin/sh

# Sound & Video
folder_path+=('AudioVideo')
folder_name+=('Sound & Video')
folder_categories+=("['AudioVideo','Audio','Video']")

# Development
folder_path+=('Development')
folder_name+=('Development')
folder_categories+=("['Development']")

# Education
folder_path+=('Education')
folder_name+=('Education')
folder_categories+=("['Education']")

# Games
folder_path+=('Games')
folder_name+=('Games')
folder_categories+=("['Game']")

# Graphics
folder_path+=('Graphics')
folder_name+=('Graphics')
folder_categories+=("['Graphics']")

# Network
folder_path+=('Network')
folder_name+=('Network')
folder_categories+=("['Network']")

# Office
folder_path+=('Office')
folder_name+=('Office')
folder_categories+=("['Office']")

# Science
folder_path+=('Science')
folder_name+=('Science')
folder_categories+=("['Science']")

# Settings
folder_path+=('Settings')
folder_name+=('Settings')
folder_categories+=("['Settings']")

# System Tools
folder_path+=('System')
folder_name+=('System Tools')
folder_categories+=("['System']")

# Utilities
folder_path+=('Utilities')
folder_name+=('Utilities')
folder_categories+=("['Utility']")

