#!/bin/sh

# Games
folder_path+=('Games')
folder_name+=('Games')
folder_categories+=("['Game']")

# Graphics
folder_path+=('Graphics')
folder_name+=('Graphics')
folder_categories+=("['Graphics','VectorGraphics']")

# Development
folder_path+=('Development')
folder_name+=('Development')
folder_categories+=("['Development']")

# Network
folder_path+=('Network')
folder_name+=('Network')
folder_categories+=("['Network']")

# Office
folder_path+=('Office')
folder_name+=('Office')
folder_categories+=("['Office']")

# Sound & Video
folder_path+=('AudioVideo')
folder_name+=('Sound & Video')
folder_categories+=("['AudioVideo']")

# System Tools
folder_path+=('System')
folder_name+=('System Tools')
folder_categories+=("['System']")

# Utilities
folder_path+=('Utilities')
folder_name+=('Utilities')
folder_categories+=("['Utility']")

# Other
folder_path+=('Other')
folder_name+=('Other')
folder_categories+=("['Settings']")

